//
//  ContentBlockerProvider.swift
//  Shut Up Core
//
//  Created by Ricky Romero on 6/23/20.
//  Copyright © 2020 Ricky Romero. All rights reserved.
//

import Foundation

final class ContentBlockerProvider {
    func coalesce() -> [ContentBlockerRule] {
        let selectors = [
            "#watch-comment-panel",
            "#cm",
            "#watch-comments-core",
            "#watch-discussion",
            "#comments-test-iframe",
            "ytm-comment-section-renderer",
            ".comments:not(code)",
            ".Comments:not(code)",
            "#comments:not(code)",
            "#Comments:not(code)",
            "#comments_container",
            "#disqus_thread",
            "#dsq-content",
            ".block-talkback_story",
            "#prodReviews",
            ".revcontent",
            ".commentlist",
            "#commentlisting",
            "#socialcomments",
            "#commentwrapper",
            ".commentwrapper",
            ".commentarea",
            "#story-comments",
            ".comment",
            "#commentform",
            ".commentText",
            "div#pluckcomments",
            "div#page div#content h2#shoutbox",
            "div#page div#content div#shoutboxContainer",
            "div#shoutbox section.shoutbox",
            "#latest-comments",
            ".commentHolder",
            ".comment-container",
            "#comment-container",
            "#comment_container",
            "#commentblob",
            "#cnnComments",
            "#BrowseComments",
            ".fa-comment",
            ".comment-count",
            "#showcomments",
            ".comments__btn",
            ".mwpphu-comments",
            ".ugccmt-comments",
            ".comments-body",
            ".articleComments",
            ".pluck-comm",
            ".page-comments",
            "#gmi-CCommentMaster",
            "div[data-hook=comments_thread]",
            ".comments-container",
            "#media_comments",
            "#idc-container-parent",
            "#livefyre_comment_stream",
            "#livefyre-body",
            "#livefyre",
            ".fyre",
            "#articleComments",
            ".js-CommentsArea",
            "#readerComments",
            ".readerComments",
            "#commentsContainer",
            ".commentsContainer",
            ".commentsModule",
            "span.postMetaHeaderCommentCount.commentCount",
            "button.comments-button",
            "a.commentCountLink",
            "p.theme-comments",
            ".comments-button",
            ".dna-comment",
            ".nw-c-comment",
            ".view-6",
            ".space-_5",
            ".all_comments",
            "#display_comments",
            ".article-comments",
            "#commentscontainer",
            ".echo-stream-container",
            "#feedback",
            "#lf_comments",
            "#lf_twitter_comments",
            "#lf_facebook_comments",
            "#lf_comment_stream",
            "#commentList",
            "#inferno-comments",
            ".cb_block",
            ".CMT_CommentList",
            "#comments_section",
            ".fb-comments",
            ".UFIComment",
            "fb\\:comments",
            "div[data-testid^=UFI2CommentsList]",
            "[aria-label^=\"Comment\"]",
            "[aria-label^=\"Reply\"]",
            "#responses",
            "#facebook_responses",
            "#facebook_conversations",
            "#fb_comments_wrapper",
            "#fb_comments_control",
            ".fb-comments-area",
            "#respond",
            "#badge_voting",
            ".spCommentsBoxBody",
            "#spArticleFunctionForum",
            "body[data-guj-zone~=\"forum\"]#postList",
            "#js-article-comments-box-form",
            ".spInteractionMarks",
            ".clearfix.article-comments-box.module-box",
            "a[href*=\"detail_tab_comments\"]",
            ".vhb-comments-container",
            ".hcf-article.hcf-content.hcf-article-type2",
            ".kommentare_uebersicht",
            "#body_dlt",
            "#comment_box_article",
            "#ugc-container",
            "#gs-social-comments",
            ".gig-comments-container",
            ".ArtikelKommentieren",
            ".tsr-Base_ContentMetaItem-social-feedback",
            "#lesermeinungen",
            ".comment-avatar-wrap",
            ".fbFeedbackContent",
            ".pluck-wrap",
            "#media-comments",
            "#d2-root",
            ".thyme-comment-list",
            ".commentsList",
            ".commentsList__item.commentItem",
            ".commentPopover",
            "#vanilla-comments",
            ".replies-wrapper>.replies",
            ".view-comment-list",
            ".js_replies",
            "#tsnYourCallStory",
            ".NB-feed-story-comments",
            ".b-comments_page",
            ".hdn-comments",
            "#cmComments",
            ".rtb-apps-comments-container",
            ".communityCanvas",
            "section#story-community.story-community",
            "#commentbox",
            "#newcommentform",
            "#QuickRegCon",
            ".inpagecomments",
            ".modCon.modConComments",
            ".full.community.page.last.even",
            "#commentsRoot",
            ".Comment",
            "#conversations-huffpost-web-main",
            ".hcf-detail.hcf-comments-container",
            "section#promoted-comments",
            "aside.comments-hotness",
            "a.comment-count",
            "div.comments-bar",
            ".summary-comments",
            ".post-content.annotation-footnote-wrapper",
            ".post-content.annotateButton",
            "#comments-container",
            ".post-comments-module",
            "#comments-count",
            ".comments-body-container",
            ".m-hero__comment-count",
            ".comment_count",
            ".m-comment-count__bubble",
            ".m-stream__node-list__comments",
            "[data-ui=comment]",
            ".liste_reactions",
            "#reagir",
            "#conversations-huffpost-web",
            "#civil-comments",
            ".post-comment",
            ".confab",
            "#dynamiccomments",
            ".comments-block",
            ".js-comments-block",
            ".comment_area",
            "#cbox_module",
            ".cmt_view",
            ".viafoura",
            ".responsesWrapper",
            ".responsesStreamWrapper",
            "#boxComentarios",
            "#comentarios",
            "#article-comments",
            ".abril-comentarios-widget",
            ".replies_wrap>div:first-child",
            "#pv_comments.wall_module",
            "#mv_comments.wall_module",
            ".pl_video_comment_post_and_comments",
            ".reacties",
            "#reacties",
            ".comments-link-wrapper",
            ".comments_article",
            "#comments-frame",
            "#commenting",
            ".is-comments-widget",
            "#comments-list",
            ".teaser.teaser_footer>a",
            "a.button.annotation-count",
            "#right-column.chat-room",
            ".right-column.chat-room__container",
            ".channel-page__right-column.chat__container",
            ".chat-pane.chat-pane__chat-list",
            "div[data-a-target=\"right-column-chat-bar\"]",
            "#watch-sidebar-live-chat",
            "ytd-live-chat-frame",
            ".js-comments-thread-container",
            "[data-test-tag=\"comment-row\"]",
            "[data-tag=\"comment-row\"]",
            "ul.Mr508",
            "article._8Rm4L div.ybXk5",
            "article._8Rm4L a.r8ZrO",
            "div#root section.dBUetj",
            "#js-mount-point-comment-module",
            ".comment-list",
            "div#root div.jUvQSR",
            "#YDC-MainCanvas.canvas-share-buttons>div:last-child",
            ".sppre_conversation-view",
            ".commentthread_area",
            ".contentCol.forum",
            ".threaded_comments",
            ".topcomment",
            ".bottom-comments",
            "iframe[src*=\"ffx.io/api/comments\"]",
            ".opinary-iframe",
            ".opinary-widget-wrapper",
            ".apester-fill-content",
            ".comment-button",
            ".media-icon--comments",
            ".a-article-meta__icon--comments",
            "#comments_container",
            ".kommentare_lesen_link",
            ".forenbeitraege_show",
            "a[name=\"meldung.newsticker.header.kommentarelesen\"]",
            ".kommentare-info",
            "span[title*=\"#comments\"]",
            ".MtnCommentScroll",
            "#ContentPlaceHolder1_FieldsetCommentEditor",
            "#ContentPlaceHolder1_ButtonCommentPublish",
            ".shares.count",
            "#maclife #comments",
            "a[href*=\"#respond\"]",
            "a[href*=\"#comments\"]",
            ".article__comments-link",
            "#comments+#weiterethemen",
            ".comment-section",
            ".modComments",
            "#kommentare",
            "#hcf-comment-wrapper.hcf-comments",
            "#commentInput.hcf-comments-input",
            ".hcf-comments",
            ".pdb-article-comments",
            ".o-teaser__comment-count",
            "div[data-external-component=\"User.Article.Likes\"]",
            "#article #commentForm",
            "a[data-disqus-identifier]",
            "#talk_community",
            ".article-content.engagement",
            "a[href*=\"#kommentare\"]",
            "#show-comments-container",
            ".article-comments",
            "body[ng-app=\"pdaily\"]a.discussions",
            ".discussion_body",
            ".tabs_container li:last-child",
            ".id-Comment",
            ".pq-comment-form-wrap",
            ".rspec-comments-total",
            "#hypercomments_widget",
            "#vuukle-comments",
            "#comments_content",
            "#comm_show_more",
            "a[name=\"komentarze\"]",
            ".comments__spotim",
            "iframe[src*=\"comments.app\"]",
            "iframe[src*=\"comments.ign.com\"]",
            "[class^=main]div[class^=content]div[data-test^=thread]",
            "#commentsTitle",
            "#commentsTitle+ul",
            "#commentsTitle+ul+span",
            ".article__reactions",
            "#commentsBox",
            "div.js-replies-to.replies-after article+article",
            "div.js-tweet-replies article",
            "div.js-conversation-show-more.conversation-more",
            "div.pod-body.review",
            ".reviews-section-wrap",
            "div.detail-characters-list~div.borderDark",
            ".content form~a#ci~div[id^=c0]",
            ".content form~a#ci~div[id^=c1]",
            ".content form~a#ci~div[id^=c2]",
            ".content form~a#ci~div[id^=c3]",
            ".content form~a#ci~div[id^=c4]",
            ".content form~a#ci~div[id^=c5]",
            ".content form~a#ci~div[id^=c6]",
            ".content form~a#ci~div[id^=c7]",
            ".content form~a#ci~div[id^=c8]",
            ".content form~a#ci~div[id^=c9]",
            "[id*=commentaires i]",
            "[class*=commentaires i]",
            ".comments-list",
            "#blogComments",
            "#comments_pane",
            "#commentcontainer",
            "#commentsDiv",
            "#comment_entries",
            "#comment_form",
            "#commentlist",
            "#user-comments",
            ".comments_area",
            ".comments-area",
            ".discussionContainer",
            ".commentBoxStyle",
            ".pagecomment",
            ".pagecommentheader",
            ".com_text",
            ".commenttxt",
            ".post-comments",
            ".post-comment-list",
            ".user_comment",
            ".widget-comments",
            "#cmtWrapper"
        ]
//        let selectors = Stylesheet.main.selectors
        Whitelist.main.load(force: true)
        let whitelist = Whitelist.main.entries

        let rules = selectors.map { selector -> ContentBlockerRule in
            let trigger = ContentBlockerRuleTrigger(
                unlessDomain: whitelist.map { "*\($0)" }
            )
            let action = ContentBlockerRuleAction(
                type: "css-display-none",
                selector: selector
            )

            return ContentBlockerRule(trigger: trigger, action: action)
        }

        return rules
    }
}
